version: 0.2

phases:
  install:
    runtime-version:
      python: 3.9
    commands:
      - echo Installing dependencies
      - pip install -r requirements.txt
  pre_build:
      commands:
        - printenv > .env
  build:
    commands:
      - echo Build started on `date`
      - echo Running nox
      - nox -rs test_ci

artifacts:
  files:
    - '**/*'

reports:
  pytest_reports:
    files:
      - pytest_report.xml
    base-directory: pytest_reports/
    file-format: JUNITXML
