version: '4.1'

services:
  cpr_dev:
    container_name: cpr
    image: postgres
    restart: always
    ports:
      - 5432:5432

    environment:
      - POSTGRES_DB=cpr_dev
      - POSTGRES_USER=cpr_dev
      - POSTGRES_PASSWORD=Cprdev@14

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=pradeepika.junapudi@vearc.com
      - PGADMIN_DEFAULT_PASSWORD=Chanti@14
