# Generated by Django 4.0.4 on 2022-05-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alliance',
            fields=[
                ('alliance_id', models.IntegerField(max_length=2, primary_key=True, serialize=False)),
                ('alliance_name', models.CharField(max_length=50)),
            ],
        ),
    ]
