# Generated by Django 4.1.1 on 2022-12-30 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('air', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_receive_quarter', models.CharField(max_length=10)),
                ('client_name', models.CharField(max_length=255)),
                ('traveller_name', models.CharField(max_length=255)),
                ('booked_date_or_invoice_date', models.DateField(null=True)),
                ('departure_date', models.DateField()),
                ('class_of_service_code', models.CharField(max_length=2)),
                ('tour_code', models.CharField(max_length=20, null=True)),
                ('ticket_designator', models.CharField(max_length=20, null=True)),
                ('point_of_sale', models.CharField(max_length=20, null=True)),
                ('fare', models.FloatField()),
                ('tax', models.FloatField()),
                ('miles_or_mileage', models.FloatField()),
                ('pnr_locator', models.CharField(max_length=20, null=True)),
                ('discount', models.FloatField()),
                ('invoice_number', models.CharField(max_length=20, null=True)),
                ('currency_code', models.CharField(max_length=3, null=True)),
                ('carrier_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='air.airline')),
                ('destination_airport_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_airport_code', to='air.airport')),
                ('origin_airport_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_airport_code', to='air.airport')),
            ],
        ),
    ]
