# Generated by Django 4.0.4 on 2022-05-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alliance',
            name='alliance_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
