# Generated by Django 4.0.4 on 2022-09-09 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('air', '0002_preference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airline',
            old_name='carrier_alliance_code',
            new_name='carrier_alliance',
        ),
    ]
