# Generated by Django 4.0.4 on 2022-05-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air', '0002_alter_alliance_alliance_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('airport_id', models.IntegerField()),
                ('airport_code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('airport_city', models.CharField(max_length=100)),
            ],
        ),
    ]
