# Generated by Django 4.1.3 on 2022-12-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_spend_obligation_currencies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractversion",
            name="autorenewal_duration_unit",
            field=models.SmallIntegerField(
                blank=True, choices=[(1, "Day"), (2, "Week"), (3, "Month"), (4, "Year")], default=4, null=True
            ),
        ),
        migrations.AlterField(
            model_name="spendobligation",
            name="usage_unit",
            field=models.SmallIntegerField(
                blank=True,
                choices=[
                    (1, "Credit"),
                    (2, "Report"),
                    (3, "Gb"),
                    (4, "Tb"),
                    (5, "Circuit"),
                    (6, "Device"),
                    (7, "Other"),
                ],
                default=7,
                null=True,
            ),
        ),
    ]
