# Generated by Django 4.1.3 on 2022-12-16 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_coveragegrouprestriction_subscription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer_entity_name', models.TextField()),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (2, 'Upcoming'), (3, 'Expired'), (4, 'Terminated')], default=1)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('signed_date', models.DateField(blank=True, null=True)),
                ('autorenewal_duration', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('autorenewal_duration_unit', models.SmallIntegerField(blank=True, choices=[(1, 'Day'), (2, 'Week'), (3, 'Month'), (4, 'Year')], default=4, null=True)),
                ('autorenewal_deadline', models.DateField(blank=True, null=True)),
                ('terminated_at', models.DateField(blank=True, null=True)),
                ('business_deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='api.businessdeal')),
            ],
            options={
                'verbose_name_plural': 'Contracts',
                'db_table': 'contracts',
            },
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='contract_version',
        ),
        migrations.DeleteModel(
            name='ContractVersion',
        ),
        migrations.AddField(
            model_name='subscription',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='api.contract'),
        ),
    ]
