# Generated by Django 4.1.3 on 2022-12-19 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_licenseperiod_delete_spendobligation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='licenseperiod',
            options={'verbose_name_plural': 'Licenses Periods'},
        ),
    ]
