# Generated by Django 4.1.3 on 2022-12-20 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_licenseperiod_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licenseperiod',
            name='employee',
        ),
        migrations.CreateModel(
            name='EmployeeLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees_licenses', to='api.employee')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees_licenses', to='api.subscription')),
            ],
            options={
                'verbose_name_plural': 'Employees Licenses',
                'db_table': 'employees_licenses',
            },
        ),
    ]
