# Generated by Django 4.1.3 on 2022-12-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_licenseperiod_incremental_user_price_currency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="domain",
            field=models.SmallIntegerField(
                choices=[(1, "Market Data"), (2, "Technology"), (3, "Travel"), (4, "Insurance")]
            ),
        ),
    ]
