# Generated by Django 4.1.3 on 2023-01-03 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_domain_not_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="precautionary_cancellation_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
