# Generated by Django 4.1.3 on 2023-01-03 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_precautionary_cancellation_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="precautionary_cancellation_date",
            field=models.DateField(null=True),
        ),
    ]
