# Generated by Django 4.1.3 on 2023-01-04 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_alter_contract_precautionary_cancellation_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="tax_rate",
            field=models.DecimalField(decimal_places=6, max_digits=7, null=True),
        ),
    ]
