# Generated by Django 4.1.3 on 2023-01-14 00:10

from django.db import migrations, models
from api.constants import CONTRACT_DURATION_UNIT_DAYS, CONTRACT_DURATION_UNIT_WEEKS, CONTRACT_DURATION_UNIT_MONTHS


def forwards_func(apps, schema_editor):
    Contract = apps.get_model("api", "Contract")
    db_alias = schema_editor.connection.alias
    Contract.objects.using(db_alias).filter(
        autorenewal_duration_unit__in=[CONTRACT_DURATION_UNIT_DAYS, CONTRACT_DURATION_UNIT_WEEKS]
    ).update(autorenewal_duration_unit=CONTRACT_DURATION_UNIT_MONTHS)


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_remove_licenseperiod_minimum_price_and_more"),
    ]

    operations = [
        migrations.RunPython(forwards_func, migrations.RunPython.noop, elidable=True),
        migrations.AlterField(
            model_name="contract",
            name="autorenewal_duration_unit",
            field=models.SmallIntegerField(blank=True, choices=[(3, "Month"), (4, "Year")], default=4, null=True),
        ),
    ]
