# Generated by Django 4.1.3 on 2023-01-23 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_alter_product_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="previous_contract",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="api.contract"),
        ),
    ]
