# Generated by Django 4.1.3 on 2023-01-30 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_subscription_discount_type_subscription_tmc_supplier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
        migrations.AddField(
            model_name='product',
            name='types',
            field=models.ManyToManyField(db_table='product_types', to='api.producttype'),
        ),
    ]
