# Generated by Django 4.1.3 on 2023-01-27 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_remove_product_type_product_types"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractSeries",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Contract Series",
                "db_table": "contract_series",
            },
        ),
        migrations.AddField(
            model_name="contract",
            name="contract_series",
            field=models.ForeignKey(null=True, on_delete=models.deletion.PROTECT, to="api.contractseries"),
        ),
    ]
