# Generated by Django 4.1.3 on 2023-01-31 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_migrate_previous_contracts_to_contractseries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='industry',
        ),
        migrations.AddField(
            model_name='product',
            name='industries',
            field=models.ManyToManyField(db_table='product_industries', to='api.industry'),
        ),
    ]
