# Generated by Django 4.1.3 on 2023-02-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_remove_product_industry_product_industries'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='geographies',
            field=models.ManyToManyField(db_table='product_geographies', to='api.geography'),
        ),
    ]
