# Generated by Django 4.1.3 on 2023-02-01 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_product_geographies'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='geographies',
            field=models.ManyToManyField(db_table='buyer_geographies', to='api.geography'),
        ),
        migrations.AddField(
            model_name='buyer',
            name='industries',
            field=models.ManyToManyField(db_table='buyer_industries', to='api.industry'),
        ),
    ]
