# Generated by Django 4.1.3 on 2023-02-08 18:46

import api.helpers
from typing import cast

from django.apps.registry import Apps
from django.db import migrations, models
import django.db.models.deletion
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def create_default_document_type(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    from api.models.DocumentType import DocumentType

    document_type_model: DocumentType = cast(DocumentType, apps.get_model("api", "DocumentType"))
    db_alias = schema_editor.connection.alias
    document_type_model.objects.using(db_alias).create(name="Default")


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_delete_supplier_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Document Types',
                'db_table': 'documents_types',
            },
        ),
        # Add a default DocumentType row to the DB (existing documenttypes will FK to this type after migrations ran)
        migrations.RunPython(create_default_document_type, migrations.RunPython.noop),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
                ('date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=api.helpers.derive_subdir_path_based_on_fk_fields)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.buyer')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.contract')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.product')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.supplier')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.documenttype')),
            ],
            options={
                'verbose_name_plural': 'Documents',
                'db_table': 'documents',
            },
        ),
    ]
