# Generated by Django 4.1.3 on 2023-02-09 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0032_documenttype_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="autorenewal_duration",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contract",
            name="autorenewal_duration_unit",
            field=models.SmallIntegerField(blank=True, choices=[(3, "Month(s)"), (4, "Year(s)")], null=True),
        ),
    ]
