# Generated by Django 4.1.3 on 2023-02-13 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0033_alter_contract_autorenewal_duration_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllowedDocumentFileExtension",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.TextField()),
            ],
            options={
                "verbose_name_plural": "Allowed Document File Extensions",
                "db_table": "allowed_document_file_extensions",
            },
        ),
    ]
