# Generated by Django 4.1.1 on 2022-09-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gds_codes',
            fields=[
                ('concertiv_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('chain_code', models.CharField(max_length=2)),
                ('chain_name', models.CharField(max_length=255)),
                ('property_name', models.CharField(max_length=255)),
                ('property_address', models.CharField(max_length=255)),
                ('city_name', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
    ]
