# Generated by Django 4.1.1 on 2022-09-30 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gds_codes',
            name='concertiv_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
