# Generated by Django 4.1.1 on 2022-10-26 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_alter_gds_codes_city_name_alter_gds_codes_country_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gds_codes',
            new_name='Gdscodes',
        ),
    ]
